### ISSUE TITLE
getMeta***()でundefined文字列が紛れることがある

### ISSUE THREAD

**Issue by trrk** [carborane3/FlMMLonHTML5#3]
例えば、単に#ARTISTだけの行をMML中に入れると、metaArtistにundefinedと出ます。
おそらくMML.findMetaDescNの実装が悪いのではないかと思います。
1104行目、#ARTISTなどの後に内容があるかの確認処理と思われる部分`if (mm.length >= 3) {`とありますが「mm[2]がundefinedでなければ」という式にすべきではないでしょうか。
findMetaDescVも同じ実装となってますので直すとよいと思います。

よろしくお願いします。

**Comment by carborane3** [comment]
報告ありがとうございます。修正しました。
ActionScriptの仕様をそのまま流用していました。
