### ISSUE TITLE
バージョン表記

### ISSUE THREAD

**Issue by kosh04** [carborane3/FlMMLonHTML5#5]
FlMMLonHTML5.js が外部サイトで利用された場合の対応として、できる限りバージョン番号を明記してほしいです。

JS本体がminifyされた状態であっても、コードコメント中に埋め込む等でFlMMLonHTML5のバージョン番号が明記してあれば「いつの時点のソースコードなのか」が分かるため、何かと安心かと思います。

## 表記例

`/*! FlMMLonHTML5 v1.0 | (c) 2018, carborane3 | BSD-3-Clause | https://github.com/carborane3/FlMMLonHTML5 */`

## 参考リンク

- https://semver.org/lang/ja/
- http://www.atmarkit.co.jp/ait/articles/1003/26/news106.html

**Comment by carborane3** [comment]
ご指摘ならびに例示ありがとうございます。
表記例に倣い、以下形式のコメントを flmmlonhtml5-raw.js に追加し、minify後の flmmlonhtml5.js にも残るようにしたいと思います。
`/*! FlMMLonHTML5 v1.0.0 | (c) 2018, carborane3 | BSD-3-Clause | https://github.com/carborane3/FlMMLonHTML5 */`
バージョン番号の表記と上げ方はセマンティックバージョニングに従う形で良いかなと考えています
(インタフェース仕様が今後頻繁に変わることはなさそうなので1.0.0～としました) 。

なお記載するファイルはひとまずエントリポイントを有する flmmlonhtml5.js のみとし、例えば Worker 側の改修のみだった場合も flmmlonhtml5.js のバージョン表記を変更するといった運用にしたいです。
